### ISSUE TITLE
flip_until_delaunay failure

### ISSUE THREAD

**Issue by rob-rb** [nschloe/meshplex#130]
[trimesh_example.zip](https://github.com/nschloe/meshplex/files/6241541/trimesh_example.zip)
Hi Nico,
I get a problem again on the following mesh.

Version 0.15.14

Output:
```
control_uniqueness
faces are unique
control_uniqueness
[trimesh_example.zip](https://github.com/nschloe/meshplex/files/6241537/trimesh_example.zip)


face doubled  (181419, 182934, 182936) 2
face doubled  (181419, 182933, 182936) 2
finished with errors
```

**Comment by nschloe** [comment]
Right, `flip_until_delaunay()` might produce duplicate cells sometimes. Just call
```python
mesh.remove_duplicate_cells()
```
This will take care of it.

**Comment by rob-rb** [comment]
True I simplified the example too much. I wanted to say the following, iff I use flip_until_delaunay followed by remove_duplicate_cells I get a mesh with non-manifold edges:

import meshplex
import numpy as np

def unique_rows(a):
    # The numpy alternative `np.unique(a, axis=0)` is slow; cf.
    # <https://github.com/numpy/numpy/issues/11136>.
    b = np.ascontiguousarray(a).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
    a_unique, inv, cts = np.unique(b, return_inverse=True, return_counts=True)
    a_unique = a_unique.view(a.dtype).reshape(-1, a.shape[1])
    return a_unique, inv, cts


def control_mesh(mesh):
    s = mesh.idx_hierarchy.shape
    a = np.sort(mesh.idx_hierarchy.reshape(s[0], -1).T)
    a_unique, inv, cts = unique_rows(a)
    if cts.max() > 2:
        print("control_mesh found non-manifold edges",cts.max())
        for j in range(len(cts)):
            if cts[j] > 2:
                print(j, cts[j])
        return False
    print("good_mesh")
    return True



mesh = meshplex._reader.read("contour.obj")
control_mesh(mesh)
mesh.flip_until_delaunay()
print("removing duplicate cells", mesh.remove_duplicate_cells())
#print("removing duplicate cells", mesh.remove_duplicate_cells())
control_mesh(mesh)

**Comment by rob-rb** [comment]
Dear nico, were you able to look into this issue. Shall I try to reduce the mesh to a minimal example?

**Comment by nschloe** [comment]
Not yet. I'm hoping to get to it next week.

**Comment by rob-rb** [comment]
dear nico, any news is it a hard problem?

**Comment by nschloe** [comment]
Not yet, no. Still busy with other things in meshplex, so not too far away from it.

**Comment by rob-rb** [comment]
hi nico, is there any progress or information about this issue. I just need some information for my team.
best

**Comment by nschloe** [comment]
I'm looking at it right now. You never know how deep the rabbit hole goes, but I'm hoping to get it done this afternoon.

Let's kick it off with an MWE:
```python
import numpy as np
import npx

import meshplex


def control_mesh(mesh):
    s = mesh.idx_hierarchy.shape
    a = np.sort(mesh.idx_hierarchy.reshape(s[0], -1).T)
    _, cts = npx.unique_rows(a, return_counts=True)
    if cts.max() > 2:
        print("control_mesh found non-manifold edges", cts.max())
        for idx in np.where(cts > 2)[0]:
            print(idx, cts[idx])
    else:
        print("good_mesh")


points = [
    [0.011, 0.21, 0.69],
    [0.664, 0.70, 0.69],
    [0.664, 0.96, 1.43],
    [0.619, 0.96, 1.44],
    [0.664, 0.93, 1.44],
    [1.374, 0.21, 0.69],
    [0.670, 0.96, 1.44],
]
cells = [[2, 0, 1], [2, 3, 0], [4, 0, 3], [4, 6, 5], [2, 5, 6]]

mesh = meshplex.MeshTri(points, cells)

control_mesh(mesh)

print("flip")
mesh.flip_until_delaunay()

control_mesh(mesh)
```

**Comment by krober10nd** [comment]
Isn’t this a round off error when evaluating the flip predicate? Flips are notorious for this...

**Comment by rob-rb** [comment]
yes I remember robustness issues in geometric algorithms. 
offsetting 2d-curves in CAD (like rhino-cad) fails and with a random small translation they work again.
with gpc I had issues with a probability of about 1e-4. When it failed I had to do some random translation. With polygon_clipper no robustness issues so far. Do you think random translation could help?

**Comment by krober10nd** [comment]
I'm not sure how the code is compiled on the back end by your hardware, but in my experience IFort enables unsafe math ops by default while GNU based machines do not. Generally if we want to repeat work, we thus use GNU with safe math ops

**Comment by nschloe** [comment]
Here's an even simpler MWE:
```python
import numpy as np
import npx

import meshplex


def control_mesh(mesh):
    s = mesh.idx_hierarchy.shape
    a = np.sort(mesh.idx_hierarchy.reshape(s[0], -1).T)
    _, cts = npx.unique_rows(a, return_counts=True)
    if cts.max() > 2:
        print("control_mesh found non-manifold edges", cts.max())
        for idx in np.where(cts > 2)[0]:
            print(idx, cts[idx])
    else:
        print("good_mesh")


points = [
    [0.0, 0.0, 0.0],
    [1.0, 0.5, 0.0],
    [1.0, 0.76, 1.0],
    [1.0, 0.8, 1.0],
    [1.0, 0.7, 1.0],
    [1.0, 0.7, 0.0],
    [1.0, 0.8, 1.0],
]
cells = [[2, 0, 1], [2, 3, 0], [4, 0, 3], [4, 6, 5], [2, 5, 6]]

mesh = meshplex.MeshTri(points, cells)
mesh.save("out0.vtu")

control_mesh(mesh)

print("flip 1...")
mesh.flip_until_delaunay(max_steps=1)
mesh.save("out1.vtu")

print("flip 2...")
mesh.flip_until_delaunay(max_steps=1)
mesh.save("out2.vtu")

print("flip 3...")
mesh.flip_until_delaunay(max_steps=1)
mesh.save("out3.vtu")

control_mesh(mesh)

mesh = meshplex.MeshTri(mesh.points, mesh.cells("points"))
mesh.save("out4.vtu")
```
![screenshot](https://user-images.githubusercontent.com/181628/115889644-672ad300-a454-11eb-8dc9-e37431a7c1f1.png)

So, this situation is a little crazy to start out with. It's not too strange that the edge flipper produces non-manifold edges.

**Comment by rob-rb** [comment]
what are the options.  Do you think it is better to find some preprocessing step or a postprocessor to solver the non-manifold edges?

**Comment by rob-rb** [comment]
While the first MWE is a "good" mesh according to Rhino the second MWE has self-intersections. 
Are those MWE's subsets of the original geometry?

**Comment by nschloe** [comment]
> While the first MWE is a "good" mesh according to Rhino the second MWE has self-intersections.
> Are those MWE's subsets of the original geometry?

I moved the points around a bit, maybe that's causing the hickup in Rhino. Self-intersections aren't a problem in meshplex. I'm debugging right now, might have to drag it into the weekend.

**Comment by nschloe** [comment]
I just found a bug where flips don't happen correctly if a cell is exactly degenerate. Probably not the issue here, but maybe a fix will already do some good.

**Comment by nschloe** [comment]
So, I've fixed the issue by disallowing edge flips into existing edges altogether. This can break the promise of creating Delaunay meshes, but I added a user warning about that. The non-manifold edges seemed to create more trouble than non-Delaunay edges would.

**Comment by rob-rb** [comment]
I worked now with 1.62.2 and still get similar problems.

[trimesh_example.zip](https://github.com/nschloe/meshplex/files/6371940/trimesh_example.zip)

I tried to make some mwe-extracting code. Maybe you have to help me once again understanding what is the idx-structure.

**Comment by nschloe** [comment]
The last entry `idx[-1]` is what was previously `idx_hierarchy`, i.e., an array associating point indices with cells/facets/edges. The entries before that associate edges with facets/cells, facets with cells etc.
